Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:root@tcp(127.0.0.1:3306)/messi?parseTime=True&loc=Local"
  DatabaseName: "messi"
  Username: "root"
  Password: "root"


JwtSettings:
  SecretKey: "haoruipeng"
